# Generated by Django 5.1.6 on 2025-03-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('methode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Carte Bancaire', 'Carte Bancaire')], max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.eleve')),
            ],
        ),
    ]
